plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'dev.kikugie.stonecutter'
    id 'net.neoforged.moddev'
    id 'org.jetbrains.kotlin.jvm'
}

version = mod_version
group = mod_group_id

if (minecraft_version != stonecutter.current.version) {
    throw new GradleException("Minecraft version ${minecraft_version} does not match Stonecutter target ${stonecutter.current.version}")
}

repositories {
    mavenCentral()
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
        content { includeGroup 'thedarkcolour' }
    }
}

base {
    archivesName = "${mod_name}-${minecraft_version}-neoforge"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
kotlin.jvmToolchain(java_version as int)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            gameDirectory = layout.projectDirectory.dir('run/client')
        }
        server {
            server()
            programArgument '--nogui'
            gameDirectory = layout.projectDirectory.dir('run/server')
        }
        gameTestServer {
            type = 'gameTestServer'
            gameDirectory = layout.projectDirectory.dir('run/gameTestServer')
        }
        data {
            data()
            gameDirectory = layout.projectDirectory.dir('run/data')
            programArguments.addAll '--mod', project.mod_id, '--all', '--output',
                layout.projectDirectory.dir('src/generated/resources').asFile.absolutePath, '--existing',
                rootProject.file('src/main/resources').absolutePath
        }
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources.srcDirs rootProject.file('src/generated/resources'), layout.projectDirectory.dir('src/generated/resources')

dependencies {
    implementation "thedarkcolour:kotlinforforge-neoforge:${kotlin_for_forge_version}"
}

def generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    def replaceProperties = [
        minecraft_version_range: minecraft_version_range,
        neo_version_range      : neo_version_range,
        loader_version_range   : loader_version_range,
        mod_id                 : mod_id,
        mod_name               : mod_name,
        mod_license            : mod_license,
        mod_version            : mod_version,
        mod_authors            : mod_authors,
        mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from rootProject.file('src/main/templates')
    into layout.buildDirectory.dir('generated/modMetadata')
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = "${mod_id}-${minecraft_version}-neoforge"
            from components.java
        }
    }
    repositories {
        maven {
            url = rootProject.layout.projectDirectory.dir('repo').asFile.toURI()
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
