org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.stdlib.default.dependency=false
dev.kikugie.stonecutter.hard_mode=true

mod_id=kvxstorage
mod_name=KVXStorage
mod_license=MIT
mod_version=0.1.0
mod_group_id=org.kvxd
mod_authors=kvxd
mod_description=A simple yet powerful storage solution
