org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
dev.kikugie.stonecutter.hard_mode=true

mod_id=sophisticatedintegrations
mod_name=Sophisticated Integrations
mod_license=MIT
mod_version=0.1.1
mod_group_id=org.kvxd
mod_authors=kvxd
mod_description=Connects Tom's Simple Storage terminals with Sophisticated Backpacks and recipe viewers.
